### ISSUE TITLE
出现问题的改动呢？

### ISSUE THREAD

**Issue by iZaiZaiA** [CN-HM/MP-CU-Test#1]
我看了，目前mp-cu没什么改动啊，你把出问题的代码，提交一下。

**Comment by CN-HM** [comment]
前面邮件已经讲了，我改了图片模块作为demo，你首页面点击图片模块进去就是demo页面。



***@***.***
 
发件人： ZaiZai
发送时间： 2022-01-22 13:18
收件人： CN-HM/MP-CU-Test
抄送： Subscribed
主题： [CN-HM/MP-CU-Test] 出现问题的改动呢？ (Issue #1)
我看了，目前mp-cu没什么改动啊，你把出问题的代码，提交一下。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iZaiZaiA** [comment]
> 前面邮件已经讲了，我改了图片模块作为demo，你首页面点击图片模块进去就是demo页面。 

问题是，你现在仓库里的代码，跟我的没区别啊，而且，我下载到本地，真机跑了一遍，也并没有出现导致小程序崩溃，而你所讲的`catchtap="_preview" ` 我也没看见你改在什么地方。

**Comment by CN-HM** [comment]
我的我的，上传错了文件夹



***@***.***
 
发件人： ZaiZai
发送时间： 2022-01-22 13:18
收件人： CN-HM/MP-CU-Test
抄送： Subscribed
主题： [CN-HM/MP-CU-Test] 出现问题的改动呢？ (Issue #1)
我看了，目前mp-cu没什么改动啊，你把出问题的代码，提交一下。
―
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iZaiZaiA** [comment]
> 我的我的，上传错了文件夹 

你是想点击后，预览图片，还是不预览图片？

**Comment by CN-HM** [comment]
目的是让radio内嵌套的img能被点击预览。



***@***.***
 
发件人： ZaiZai
发送时间： 2022-01-22 13:46
收件人： CN-HM/MP-CU-Test
抄送： Soup_HM; Comment
主题： Re: [CN-HM/MP-CU-Test] 出现问题的改动呢？ (Issue #1)
我的我的，上传错了文件夹
你是想点击后，预览图片，还是不预览图片？
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iZaiZaiA** [comment]
> 目的是让radio内嵌套的img能被点击预览。

已修复，但我无法给你的仓库提交代码，没权限。。

修复代码如下：

`ui-img` 和 `ui-img-test` 组件里，修改`current`参数的默认值为0，然后，把组件里`catchtap`还原为`bindtap`。

再在`image`的demo里，添加代码：` catchtap="testCatchTap" `

也就说把，在组件里，不用阻止冒泡事件，再demo的引用处使用阻止事件来阻止单选框的选中。

具体代码如下：

`ui-img-test` 组件里

```
current: {
    type: Number,
    value: 0
},
```

wxml里

```
bindtap="_preview"
```

`image`的demo里

```
<ui-img-test preview slot="icon" src="{{list[index]}}" catchtap="testCatchTap"/>

//js
testCatchTap() {
    console.log('阻止radio')
}
```

导致崩溃的原因是，current参数，默认为-1，`wx.previewImage`的 current 为 -1 时就会导致小程序崩溃

也就是说，ui-img-test组件，实际上没啥用了。。

**Comment by CN-HM** [comment]
膜拜大佬~ 
但是功能上我想的是保留单选框选中事件，仅当点击区域为图片区域的时候才触发图片预览功能。
我找了半天，没想到会是current为-1导致。
感谢感谢~



***@***.***
 
发件人： ZaiZai
发送时间： 2022-01-22 14:33
收件人： CN-HM/MP-CU-Test
抄送： Soup_HM; Comment
主题： Re: [CN-HM/MP-CU-Test] 出现问题的改动呢？ (Issue #1)
目的是让radio内嵌套的img能被点击预览。
已修复，但我无法给你的仓库提交代码，没权限。。
修复代码如下：
ui-img 和 ui-img-test 组件里，修改current参数的默认值为0，然后，把组件里catchtap还原为bindtap。
再在image的demo里，添加代码：catchtap="testCatchTap"
也就说把，在组件里，不用阻止冒泡事件，再demo的引用处使用阻止事件来阻止单选框的选中。
具体代码如下：
ui-img-test 组件里
current: {
    type: Number,
    value: 0
},

wxml里
bindtap="_preview"

image的demo里
<ui-img-test preview slot="icon" src="{{list[index]}}" catchtap="testCatchTap"/>
//js
testCatchTap() {
    console.log('阻止radio')
}

导致崩溃的原因是，current参数，默认为-1，wx.previewImage的 current 为 -1 时就会导致小程序崩溃
也就是说，ui-img-test组件，实际上没啥用了。。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iZaiZaiA** [comment]
> 膜拜大佬~ 但是功能上我想的是保留单选框选中事件，仅当点击区域为图片区域的时候才触发图片预览功能。 我找了半天，没想到会是current为-1导致。 感谢感谢~ 

现在就是这样的。

```
<ui-img-test preview slot="icon" src="{{list[index]}}" catchtap="testCatchTap"/>
```

catchtap 挂在 ui-img-test 上后，只有图片被点击，才会阻止单选框冒泡，点击其它区域，不会影响单选框选中。
